services:
  - type: web
    name: my-todo-backend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: web
    name: my-todo-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist 