services:
  - type: web
    name: collaborative-task-manager-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 